In [3]:
import numpy as np
import pandas as pd
a=np.array([[10,20,30],[20,30,40],[30,40,50]])
print(a)
print(a.shape) #returns array dimensions in a tuple form

[[10 20 30]
 [20 30 40]
 [30 40 50]]
(3, 3)


In [4]:
print('THE DIMENSIONS',a.ndim)
print('THE SIZE',a.size)
print('THE TYPE',a.dtype)
print('AFTER CHANGING THE TYPE',a.astype('string_'))

THE DIMENSIONS 2
THE SIZE 9
THE TYPE int64
AFTER CHANGING THE TYPE [[b'10' b'20' b'30']
 [b'20' b'30' b'40']
 [b'30' b'40' b'50']]


In [5]:
#manipulation
print(np.random.randint(20))
scale=1.0
rnum=np.random.binomial(10,0.2,size=(5,5))
print("RANDOM NUMBER DISTRUBUTION FROM BINOMIAL:")
print(rnum)
tr=np.transpose(rnum)
print(tr)
print(tr.flatten())


3
RANDOM NUMBER DISTRUBUTION FROM BINOMIAL:
[[2 3 3 3 2]
 [1 4 2 3 0]
 [2 2 3 0 3]
 [2 4 3 1 3]
 [4 0 2 1 5]]
[[2 1 2 2 4]
 [3 4 2 4 0]
 [3 2 3 3 2]
 [3 3 0 1 1]
 [2 0 3 3 5]]
[2 1 2 2 4 3 4 2 4 0 3 2 3 3 2 3 3 0 1 1 2 0 3 3 5]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([1, 2, 3, 4])
np.resize(arr, (2, 3))

array([[1, 2, 3],
       [4, 1, 2]])

In [8]:
arr = np.array([1, 2, 3])
new_arr = np.insert(arr, 1, 99)
print(new_arr)

[ 1 99  2  3]


In [9]:
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5])
print(new_arr)

[1 2 3 4 5]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [1, 3])
print(new_arr)

[1 3 5]


In [11]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3 4 5]


In [12]:
arr = np.array([1, 2, 3])
arr_copy = np.copy(arr)
print(arr_copy)

[1 2 3]


In [13]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
view_arr[1] = 99

print(arr)
print(view_arr)


[ 1 99  3  4]
[ 1 99  3  4]


In [15]:
#basic operations and functions

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
add_result = np.add(arr1, arr2)
print(add_result)
sub_result = np.subtract(arr1, arr2)
print(sub_result)
mul_result = np.multiply(arr1, arr2)
print(mul_result)
div_result = np.divide(arr1, arr2)
print(div_result)
sum_result = np.sum(arr1)
print(sum_result)
min_result = np.min(arr1)
print(min_result)
max_result = np.max(arr1)
print(max_result)
mean_result = np.mean(arr1)
print(mean_result)
sorted_arr = np.sort(arr1)
print(sorted_arr)

#arrage
arr = np.arange(10)
print(arr)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
10
1
4
2.5
[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
